### ISSUE TITLE
Jetstream APIs

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#352]
The Java API should be extended for Jetstream functionality.  The full feature set will require header implementation, #338.
 
- [ ] Implement the equivalent of the following golang APIs
  - [ ]  nats-io/nats.go#585
  - [ ]  nats-io/nats.go#596
  - [ ]  nats-io/nats.go#599
- [ ] Enhance CI to use master or nightly build of nats-server (required to test).
- [ ] Unit Tests

Rather than varargs like golang, I'd suggest overloading the existing publish and subscribe APIs.

Some suggestions:

New APIs (add appropriate overloads for timeouts, contexts)
### Publish
- [ ] Connection.Publish - add overloads for timeout and context (or builder APIs?)  Note that overloads are likely easiest for the user and will perform better.

### Message
- [ ] Message.getJetStreamMetaData()
- [ ] Message.Ack
- [ ] Message.Nak
- [ ] Message.AckProgress
- [ ] Message.AckAndFetch
- [ ] Message.AckTerm
- [ ] static Message.ParsePublishAck (or static Connection.ParsePublishAck or Nats.ParsePubishAck())

### Consumer
- [ ] Subscriber.CreateConsumerConfiguration()
- [ ] ConsumerConfiguration.setDurable(string)
- [ ] ConsumerConfiguration.setDeliveryPolicy(DeliveryPolicy)
- [ ] ConsumerConfiguration.setStartSeq(int)
- [ ] ConsumerConfiguration.setStartTime(TBD - see STAN)
- [ ] ConsumerConfiguration.setAckPolicy(AckPolicy)
- [ ] ConsumerConfiguration.setAckWait(Duration)
- [ ] ConsumerConfiguration.setMaxDelivery(int)
- [ ] ConsumerConfiguration.setFilterSubject(string)
- [ ] ConsumerConfiguration.setReplayPolicy(ReplayPolicy)
- [ ] ConsumerConfiguration.SetSampleFrequency(string)
- [ ] ConsumerConfiguration.SetRateLimit(long)

Overload the subscribe APIs with a stream and consumer configuration
- [ ] Subscribe(..., string stream, ConsumerConfiguration)
